export { RestaurantCard } from "./Card/RestaurantCard";
export { Tamada } from "./Card/Tamada";
export { RandomFood } from "./Random/RandomFood";
export { RecommendationRestaurant } from "./Recommendation/RecommendationRestaurant";
export { FilterButton } from "./FilterButton";
export { TraditionalFoodLibery } from "./TraditionalFoodLibery";
// export { DetailFood, DetailModal } from ".";
export { DetailFood } from "./Detail/DetailFood";
export { DetailModal } from "./Detail/DetailModal";
export { Slide } from "./Slide";
export { Detail } from "./Detail";
